{{- if .Values.trafficSource.envoyWasm.enabled }}
{{- if .Values.trafficSource.envoyWasm.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apiclarity.name" . }}-post-install-job
  labels:
    {{ include "apiclarity.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: ["networking.istio.io"]
  resources: ["envoyfilters"]
  verbs: ["get", "list", "create", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "apiclarity.name" . }}-post-install-job
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "apiclarity.name" . }}-post-install-job
  labels:
    {{ include "apiclarity.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "apiclarity.name" . }}-post-install-job
subjects:
  - kind: ServiceAccount
    name: {{ include "apiclarity.name" . }}-post-install-job
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "apiclarity.name" . }}-post-install-job
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{ include "apiclarity.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ include "apiclarity.name" . }}-post-install-job
    spec:
      serviceAccountName: {{ include "apiclarity.name" . }}-post-install-job
      containers:
        - name: kubectl
          image: "k8s.gcr.io/hyperkube:v1.16.12"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: TRACE_SAMPLING_ENABLED
              value: "{{ .Values.global.traceSampling.enable }}"
          command:
          - /bin/bash
          - -c
          - "cd /tmp &&
{{- if .Values.trafficSource.global.httpsProxy }}
            git config --global https.proxy {{ .Values.trafficSource.global.httpsProxy }} &&
{{- end }}
{{- if .Values.trafficSource.global.httpProxy }}
            git config --global http.proxy {{ .Values.trafficSource.global.httpProxy }} &&
{{- end }}
            git clone -b {{ .Chart.AppVersion }} https://github.com/openclarity/apiclarity.git --recurse-submodules &&
            cd apiclarity/wasm-filters &&
            WASM_FILTER_TRACE_BACKEND_ADDRESS={{ include "apiclarity.name" . }}.{{ .Release.Namespace }}.svc.cluster.local ./deploy.sh {{ join " " .Values.trafficSource.envoyWasm.namespaces }}"
      restartPolicy: Never
{{- end }}
{{- end }}
