apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiclarity-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiclarity-postgresql
  template:
    metadata:
      labels:
        app: apiclarity-postgresql
    spec:
      containers:
        - name: apiclarity-postgresql
          image: rhel8/postgresql-12
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRESQL_USER
              value: postgres123
            - name: POSTGRESQL_DATABASE
              value: apiclarity
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc